// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/auth/login": {
    params: {};
  };
  "/auth/forgot-password": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/users": {
    params: {};
  };
  "/brands": {
    params: {};
  };
  "/banners": {
    params: {};
  };
  "/notifications": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/auth/login" | "/auth/forgot-password" | "/dashboard" | "/users" | "/brands" | "/banners" | "/notifications";
  };
  "pages/index.tsx": {
    id: "pages/index";
    page: "/";
  };
  "pages/auth/login.tsx": {
    id: "pages/auth/login";
    page: "/auth/login";
  };
  "pages/auth/forgot-password.tsx": {
    id: "pages/auth/forgot-password";
    page: "/auth/forgot-password";
  };
  "pages/dashboard.tsx": {
    id: "pages/dashboard";
    page: "/dashboard";
  };
  "pages/users.tsx": {
    id: "pages/users";
    page: "/users";
  };
  "pages/brands.tsx": {
    id: "pages/brands";
    page: "/brands";
  };
  "pages/banners.tsx": {
    id: "pages/banners";
    page: "/banners";
  };
  "pages/notifications.tsx": {
    id: "pages/notifications";
    page: "/notifications";
  };
};