// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

export type ContactUsEntity = {
    id: number;
    email: string;
    phone_number: string;
    phone_number_key: string;
    created_at: string;
    updated_at: string;
};

export type BrandTranslationsEntity = {
    id: number;
    brand_id: number;
    brand_translation_brand?: BrandsEntity | null;
    description: string;
    name: string;
    heading_title: string;
    language: 'ar' | 'en';
};

export type BannersEntity = {
    id: number;
    promotion_name: string;
    redirect_url: string | null;
    has_action: boolean;
    disabled: boolean;
    brand_id: number;
    image_ar_id: number;
    image_en_id: number;
    image_ar: MediaEntity;
    image_en: MediaEntity;
    brand: BrandsEntity;
    created_at: string;
    updated_at: string;
    deleted_at: string;
};

export type BrandsEntity = {
    id: number;
    name: string;
    heading_title: string;
    description: string;
    shop_url: string;
    gradient_hex: string;
    logo_id: number;
    product_picture_id: number;
    background_logo_id: number;
    display_order: number;
    logo: MediaEntity;
    product_picture: MediaEntity;
    brand_id_brand_translations: Array<BrandTranslationsEntity>;
    background_logo: MediaEntity;
    banners: Array<BannersEntity>;
    notifications: Array<NotificationsEntity>;
    created_at: string;
    updated_at: string;
    deleted_at: string;
};

export type NotificationsEntity = {
    id: number;
    title: string;
    message: string;
    link: string;
    is_read: boolean;
    user_id: number;
    brand_id: number;
    type: 'user' | 'broadcast';
    user: UsersEntity;
    brand: BrandsEntity;
    created_at: string;
    updated_at: string;
    deleted_at: string;
};

export type UsersEntity = {
    id: number;
    wallet_code: string;
    password: string;
    name: string;
    phone_number: string;
    phone_number_key: string;
    email: string;
    verification_code: string;
    verification_code_expire_at: string;
    account_verified: boolean;
    verification_code_reason: 'signup' | 'forget_password' | 'forget_password_verified' | 'complete_phone_number' | 'update_phone_number' | 'ask_update_phone_number' | 'ask_update_phone_number_verified' | 'update_email' | 'ask_update_email_verified' | 'ask_update_email';
    apple_token: string;
    google_token: string;
    facebook_token: string;
    de_square_token: string;
    de_square_token_expire_at: string;
    role: 'admin' | 'user';
    rank: 1 | 2 | 3;
    birthdate: string;
    pending_phone_number: string;
    pending_phone_number_key: string;
    pending_email: string;
    refresh_token: string;
    fcm_token: string;
    is_logged_in: boolean;
    ui_configurations: {
        [key: string]: unknown;
    } | null;
    profile_image: MediaEntity;
    notifications: Array<NotificationsEntity>;
    updated_at: string;
    created_at: string;
    deleted_at: string;
};

export type MediaEntity = {
    id: number;
    url: string;
    key: string;
    size: number;
    mime_type: string;
    format: string;
    created_at: string;
    updated_at: string;
    user: UsersEntity;
    brand_logo: BrandsEntity;
    brand_product_picture: BrandsEntity;
    brand_background_logo: BrandsEntity;
};

export type TermsEntity = {
    id: number;
    terms: string;
    policy: string;
    terms_id_terms_translations: Array<TermsTranslationsEntity>;
    created_at: string;
    updated_at: string;
    deleted_at: string;
};

export type TermsTranslationsEntity = {
    id: number;
    terms_id: number;
    terms_translation_terms?: TermsEntity | null;
    terms: string;
    policy: string;
    language: 'ar' | 'en';
};

export type ScheduledNotificationsEntity = {
    id: number;
    title: string;
    message: string;
    link: string;
    brand_id: number;
    type: 'user' | 'broadcast';
    status: 'pending' | 'processing' | 'completed' | 'failed' | 'cancelled';
    schedule_at: string;
    target_user_ids: Array<number>;
    target_ranks: Array<number>;
    processed_count: number;
    failed_count: number;
    processed_at: string;
    error_message: string;
    brand: BrandsEntity;
    created_at: string;
    updated_at: string;
    deleted_at: string;
};

export type OnboardingImagesEntity = {
    id: number;
    image_id: number;
    display_order: number;
    image: MediaEntity;
    created_at: string;
    updated_at: string;
    deleted_at: string;
};

export type CompleteForgetPasswordResponse = {
    data: {
        message: string;
    };
};

export type CompletePassword = {
    identifier: string;
    password: string;
};

export type CompletePhoneNumberResponse = {
    data: {
        otp_expire_after: number;
        phone_number: string;
    };
};

export type CompleteForgetPassword = {
    identifier: string;
    password: string;
};

export type CompletePhoneNumber = {
    phone_number: string;
    phone_number_key: string;
    name?: string;
};

export type ForgetPasswordResponse = {
    data: {
        otp_expire_after: number;
        identifier: string;
    };
};

export type ForgetPassword = {
    identifier: string;
};

export type GetSessionDataResponse = {
    data: {
        id?: number;
        email?: string;
        phone_number?: string;
        name?: string;
        role?: string;
        account_verified?: boolean;
        terms_and_conditions_accepted?: boolean;
    };
};

export type GetSessionData = {
    session_id: string;
};

export type RefreshTokenResponse = {
    data: {
        access_token: string;
        refresh_token: string;
        desquare_token: string;
        complete_phone_number_required?: boolean;
    };
};

export type RefreshToken = {
    refresh_token: string;
};

export type ResendOtpResponse = {
    data: {
        message: string;
        otp_expire_after: number;
    };
};

export type ResendOtp = {
    session_id?: string;
    identifier?: string;
};

export type SigninResponse = {
    data: {
        access_token: string;
        refresh_token: string;
        desquare_token: string;
        complete_phone_number_required?: boolean;
    };
};

export type Signin = {
    identifier?: string;
    password?: string;
    apple_token?: string;
    google_token?: string;
    facebook_token?: string;
    email?: string;
    name?: string;
    phone_number_key?: string;
};

export type Signout = {
    [key: string]: never;
};

export type SignupResponse = {
    data: {
        session_id: string;
        otp_expire_after: number;
    };
};

export type Signup = {
    phone_number: string;
    phone_number_key: string;
    email: string;
    password: string;
    name: string;
    fcm_token?: string;
    birthdate?: string;
};

export type UpdateEmail = {
    email: string;
};

export type UpdatePhoneNumber = {
    phone_number: string;
    phone_number_key: string;
};

export type VerifyOtpResponse = {
    data: {
        message: string;
        access_token?: string;
        desquare_token?: string;
    };
};

export type VerifyOtp = {
    session_id?: string;
    identifier?: string;
    otp?: string;
    phone_number_key?: string;
    fcm_token?: string;
};

export type CreateBanners = {
    promotion_name: string;
    redirect_url?: string;
    image_ar_id: number;
    image_en_id: number;
    brand_id?: number;
    has_action?: boolean;
    disabled?: boolean;
};

export type ReadBannersFilters = {
    id?: {
        $val?: string | number | Array<string | number>;
        $op: 'Eq' | 'NotEq' | 'GreaterThan' | 'LessThan' | 'GreaterThanOrEq' | 'LessThanOrEq' | 'IsNull' | 'IsNotNull' | 'In' | 'NotIn';
    };
    promotion_name?: {
        $val?: string | Array<string>;
        $op: 'Eq' | 'NotEq' | 'Contains' | 'StartsWith' | 'EndsWith' | 'IsNull' | 'IsNotNull' | 'In' | 'NotIn';
    };
    redirect_url?: {
        $val?: string | Array<string>;
        $op: 'Eq' | 'NotEq' | 'Contains' | 'StartsWith' | 'EndsWith' | 'IsNull' | 'IsNotNull' | 'In' | 'NotIn';
    };
    image_ar_id?: {
        $val?: string | number | Array<string | number>;
        $op: 'Eq' | 'NotEq' | 'GreaterThan' | 'LessThan' | 'GreaterThanOrEq' | 'LessThanOrEq' | 'IsNull' | 'IsNotNull' | 'In' | 'NotIn';
    };
    image_en_id?: {
        $val?: string | number | Array<string | number>;
        $op: 'Eq' | 'NotEq' | 'GreaterThan' | 'LessThan' | 'GreaterThanOrEq' | 'LessThanOrEq' | 'IsNull' | 'IsNotNull' | 'In' | 'NotIn';
    };
    created_at?: {
        $val?: string;
        $op: 'Eq' | 'NotEq' | 'GreaterThan' | 'LessThan' | 'GreaterThanOrEq' | 'LessThanOrEq' | 'IsNull' | 'IsNotNull';
    };
    updated_at?: {
        $val?: string;
        $op: 'Eq' | 'NotEq' | 'GreaterThan' | 'LessThan' | 'GreaterThanOrEq' | 'LessThanOrEq' | 'IsNull' | 'IsNotNull';
    };
    brand_id?: {
        $val?: string | number | Array<string | number>;
        $op: 'Eq' | 'NotEq' | 'GreaterThan' | 'LessThan' | 'GreaterThanOrEq' | 'LessThanOrEq' | 'IsNull' | 'IsNotNull' | 'In' | 'NotIn';
    };
};

export type ReadBannersOrders = {
    id?: 'asc' | 'desc';
    promotion_name?: 'asc' | 'desc';
    redirect_url?: 'asc' | 'desc';
    image_ar_id?: 'asc' | 'desc';
    image_en_id?: 'asc' | 'desc';
    created_at?: 'asc' | 'desc';
    updated_at?: 'asc' | 'desc';
};

export type ReadBannersQuery = {
    filters?: ReadBannersFilters;
    relations?: {
        image_ar?: string | boolean;
        image_en?: string | boolean;
        brand?: string | boolean | ReadBrandsRelations;
    };
    orders?: ReadBannersOrders;
    pagination?: {
        skip?: string | number;
        take?: string | number;
    };
    includeAllBranded?: string | boolean;
};

export type ReadBannersRelations = {
    image_ar?: string | boolean;
    image_en?: string | boolean;
    brand?: string | boolean | ReadBrandsRelations;
};

export type ReadOneBannersQuery = {
    relations?: ReadBannersRelations;
};

export type UpdateBanners = {
    promotion_name?: string;
    redirect_url?: string;
    image_ar_id?: number;
    image_en_id?: number;
    brand_id?: number;
    has_action?: boolean;
    disabled?: boolean;
};

export type CreateBrands = {
    name: string;
    heading_title: string;
    description: string;
    shop_url: string;
    gradient_hex: string;
    logo_id: number;
    product_picture_id: number;
    background_logo_id: number;
    display_order?: number;
    brand_id_brand_translations: Array<{
        description: string;
        name: string;
        heading_title: string;
        language: 'ar' | 'en';
    }>;
    banners?: Array<{
        id: number;
    }>;
};

export type ReadBrandsFilters = {
    id?: {
        $val?: string | number | Array<string | number>;
        $op: 'Eq' | 'NotEq' | 'GreaterThan' | 'LessThan' | 'GreaterThanOrEq' | 'LessThanOrEq' | 'IsNull' | 'IsNotNull' | 'In' | 'NotIn';
    };
    name?: {
        $val?: string | Array<string>;
        $op: 'Eq' | 'NotEq' | 'Contains' | 'StartsWith' | 'EndsWith' | 'IsNull' | 'IsNotNull' | 'In' | 'NotIn';
    };
    heading_title?: {
        $val?: string | Array<string>;
        $op: 'Eq' | 'NotEq' | 'Contains' | 'StartsWith' | 'EndsWith' | 'IsNull' | 'IsNotNull' | 'In' | 'NotIn';
    };
    description?: {
        $val?: string | Array<string>;
        $op: 'Eq' | 'NotEq' | 'Contains' | 'StartsWith' | 'EndsWith' | 'IsNull' | 'IsNotNull' | 'In' | 'NotIn';
    };
    shop_url?: {
        $val?: string | Array<string>;
        $op: 'Eq' | 'NotEq' | 'Contains' | 'StartsWith' | 'EndsWith' | 'IsNull' | 'IsNotNull' | 'In' | 'NotIn';
    };
    gradient_hex?: {
        $val?: string | Array<string>;
        $op: 'Eq' | 'NotEq' | 'Contains' | 'StartsWith' | 'EndsWith' | 'IsNull' | 'IsNotNull' | 'In' | 'NotIn';
    };
    logo_id?: {
        $val?: string | number | Array<string | number>;
        $op: 'Eq' | 'NotEq' | 'GreaterThan' | 'LessThan' | 'GreaterThanOrEq' | 'LessThanOrEq' | 'IsNull' | 'IsNotNull' | 'In' | 'NotIn';
    };
    product_picture_id?: {
        $val?: string | number | Array<string | number>;
        $op: 'Eq' | 'NotEq' | 'GreaterThan' | 'LessThan' | 'GreaterThanOrEq' | 'LessThanOrEq' | 'IsNull' | 'IsNotNull' | 'In' | 'NotIn';
    };
    created_at?: {
        $val?: string;
        $op: 'Eq' | 'NotEq' | 'GreaterThan' | 'LessThan' | 'GreaterThanOrEq' | 'LessThanOrEq' | 'IsNull' | 'IsNotNull';
    };
    updated_at?: {
        $val?: string;
        $op: 'Eq' | 'NotEq' | 'GreaterThan' | 'LessThan' | 'GreaterThanOrEq' | 'LessThanOrEq' | 'IsNull' | 'IsNotNull';
    };
};

export type ReadBrandsOrders = {
    id?: 'asc' | 'desc';
    name?: 'asc' | 'desc';
    heading_title?: 'asc' | 'desc';
    description?: 'asc' | 'desc';
    shop_url?: 'asc' | 'desc';
    gradient_hex?: 'asc' | 'desc';
    logo_id?: 'asc' | 'desc';
    product_picture_id?: 'asc' | 'desc';
    display_order?: 'asc' | 'desc';
    created_at?: 'asc' | 'desc';
    updated_at?: 'asc' | 'desc';
};

export type ReadBrandsQuery = {
    filters?: ReadBrandsFilters;
    relations?: {
        logo?: string | boolean;
        product_picture?: string | boolean;
        background_logo?: string | boolean;
        banners?: string | boolean | ReadBannersRelations;
        brand_id_brand_translations?: boolean | string;
    };
    orders?: ReadBrandsOrders;
    pagination?: {
        skip?: string | number;
        take?: string | number;
    };
};

export type ReadBrandsRelations = {
    logo?: string | boolean;
    product_picture?: string | boolean;
    background_logo?: string | boolean;
    banners?: string | boolean | ReadBannersRelations;
    brand_id_brand_translations?: boolean | string;
};

export type ReadOneBrandsQuery = {
    relations?: ReadBrandsRelations;
};

export type ReorderBrands = {
    brands: Array<{
        id: number;
        display_order: number;
    }>;
};

export type UpdateBrands = {
    name?: string;
    heading_title?: string;
    description?: string;
    shop_url?: string;
    gradient_hex?: string;
    logo_id?: number;
    product_picture_id?: number;
    background_logo_id?: number;
    display_order?: number;
    banners?: Array<{
        id: number;
    }>;
    brand_id_brand_translations?: Array<{
        id?: number | null;
        brand_id?: number | null;
        description: string;
        name: string;
        heading_title: string;
        language: 'ar' | 'en';
    }>;
};

export type CreateContactUs = {
    email: string;
    phone_number?: string;
    phone_number_key?: string;
};

export type ReadContactUsFilters = {
    id?: {
        $val?: string | number | Array<string | number>;
        $op: 'Eq' | 'NotEq' | 'GreaterThan' | 'LessThan' | 'GreaterThanOrEq' | 'LessThanOrEq' | 'IsNull' | 'IsNotNull' | 'In' | 'NotIn';
    };
    email?: {
        $val?: string | Array<string>;
        $op: 'Eq' | 'NotEq' | 'Contains' | 'StartsWith' | 'EndsWith' | 'IsNull' | 'IsNotNull' | 'In' | 'NotIn';
    };
    phone_number?: {
        $val?: string | Array<string>;
        $op: 'Eq' | 'NotEq' | 'Contains' | 'StartsWith' | 'EndsWith' | 'IsNull' | 'IsNotNull' | 'In' | 'NotIn';
    };
    phone_number_key?: {
        $val?: string | Array<string>;
        $op: 'Eq' | 'NotEq' | 'Contains' | 'StartsWith' | 'EndsWith' | 'IsNull' | 'IsNotNull' | 'In' | 'NotIn';
    };
    created_at?: {
        $val?: string;
        $op: 'Eq' | 'NotEq' | 'GreaterThan' | 'LessThan' | 'GreaterThanOrEq' | 'LessThanOrEq' | 'IsNull' | 'IsNotNull';
    };
    updated_at?: {
        $val?: string;
        $op: 'Eq' | 'NotEq' | 'GreaterThan' | 'LessThan' | 'GreaterThanOrEq' | 'LessThanOrEq' | 'IsNull' | 'IsNotNull';
    };
};

export type ReadContactUsOrders = {
    id?: 'asc' | 'desc';
    email?: 'asc' | 'desc';
    phone_number?: 'asc' | 'desc';
    created_at?: 'asc' | 'desc';
    updated_at?: 'asc' | 'desc';
};

export type ReadContactUsQuery = {
    filters?: ReadContactUsFilters;
    relations?: {
        [key: string]: never;
    };
    orders?: ReadContactUsOrders;
    pagination?: {
        skip?: string | number;
        take?: string | number;
    };
};

export type ReadContactUsRelations = {
    [key: string]: never;
};

export type ReadOneContactUsQuery = {
    relations?: ReadContactUsRelations;
};

export type UpdateContactUs = {
    email?: string;
    phone_number?: string;
    phone_number_key?: string;
};

export type CreateMedia = {
    url: string;
    key: string;
    size: number;
    mime_type: string;
    format: string;
};

export type ReadMediaFilters = {
    id?: {
        $val?: string | number | Array<string | number>;
        $op: 'Eq' | 'NotEq' | 'GreaterThan' | 'LessThan' | 'GreaterThanOrEq' | 'LessThanOrEq' | 'IsNull' | 'IsNotNull' | 'In' | 'NotIn';
    } | null;
    url?: {
        $val?: string | Array<string>;
        $op: 'Eq' | 'NotEq' | 'Contains' | 'StartsWith' | 'EndsWith' | 'IsNull' | 'IsNotNull' | 'In' | 'NotIn';
    } | null;
    key?: {
        $val?: string | Array<string>;
        $op: 'Eq' | 'NotEq' | 'Contains' | 'StartsWith' | 'EndsWith' | 'IsNull' | 'IsNotNull' | 'In' | 'NotIn';
    } | null;
    size?: {
        $val?: string | number | Array<string | number>;
        $op: 'Eq' | 'NotEq' | 'GreaterThan' | 'LessThan' | 'GreaterThanOrEq' | 'LessThanOrEq' | 'IsNull' | 'IsNotNull' | 'In' | 'NotIn';
    } | null;
    mime_type?: {
        $val?: string | Array<string>;
        $op: 'Eq' | 'NotEq' | 'Contains' | 'StartsWith' | 'EndsWith' | 'IsNull' | 'IsNotNull' | 'In' | 'NotIn';
    } | null;
    format?: {
        $val?: string | Array<string>;
        $op: 'Eq' | 'NotEq' | 'Contains' | 'StartsWith' | 'EndsWith' | 'IsNull' | 'IsNotNull' | 'In' | 'NotIn';
    } | null;
    created_at?: {
        $val?: string;
        $op: 'Eq' | 'NotEq' | 'GreaterThan' | 'LessThan' | 'GreaterThanOrEq' | 'LessThanOrEq' | 'IsNull' | 'IsNotNull';
    } | null;
    updated_at?: {
        $val?: string;
        $op: 'Eq' | 'NotEq' | 'GreaterThan' | 'LessThan' | 'GreaterThanOrEq' | 'LessThanOrEq' | 'IsNull' | 'IsNotNull';
    } | null;
};

export type ReadMediaOrders = {
    id?: 'asc' | 'desc';
    url?: 'asc' | 'desc';
    key?: 'asc' | 'desc';
    size?: 'asc' | 'desc';
    mime_type?: 'asc' | 'desc';
    format?: 'asc' | 'desc';
    created_at?: 'asc' | 'desc';
    updated_at?: 'asc' | 'desc';
};

export type ReadMediaQuery = {
    filters?: ReadMediaFilters;
    relations?: {
        [key: string]: never;
    };
    orders?: ReadMediaOrders;
    pagination?: {
        skip?: string | number;
        take?: string | number;
    };
};

export type ReadMediaRelations = {
    [key: string]: never;
};

export type ReadOneMediaQuery = {
    relations?: ReadMediaRelations;
};

export type CreateBarqNotification = {
    title: string;
    message: string;
    phone_number: string;
};

export type CreateBroadcastNotification = {
    title: string;
    message: string;
    link?: string;
    brand_id?: number;
    ranks?: Array<1 | 2 | 3>;
    schedule_at?: string;
};

export type CreateNotification = {
    title: string;
    message: string;
    link?: string;
    brand_id?: number;
    users?: Array<number>;
    ranks?: Array<1 | 2 | 3>;
    schedule_at?: string;
};

export type ReadNotificationFilters = {
    id?: {
        $val?: string | number | Array<string | number>;
        $op: 'Eq' | 'NotEq' | 'GreaterThan' | 'LessThan' | 'GreaterThanOrEq' | 'LessThanOrEq' | 'IsNull' | 'IsNotNull' | 'In' | 'NotIn';
    };
    title?: {
        $val?: string | Array<string>;
        $op: 'Eq' | 'NotEq' | 'Contains' | 'StartsWith' | 'EndsWith' | 'IsNull' | 'IsNotNull' | 'In' | 'NotIn';
    };
    message?: {
        $val?: string | Array<string>;
        $op: 'Eq' | 'NotEq' | 'Contains' | 'StartsWith' | 'EndsWith' | 'IsNull' | 'IsNotNull' | 'In' | 'NotIn';
    };
    link?: {
        $val?: string | Array<string>;
        $op: 'Eq' | 'NotEq' | 'Contains' | 'StartsWith' | 'EndsWith' | 'IsNull' | 'IsNotNull' | 'In' | 'NotIn';
    };
    user_id?: {
        $val?: string | number | Array<string | number>;
        $op: 'Eq' | 'NotEq' | 'GreaterThan' | 'LessThan' | 'GreaterThanOrEq' | 'LessThanOrEq' | 'IsNull' | 'IsNotNull' | 'In' | 'NotIn';
    };
    created_at?: {
        $val?: string;
        $op: 'Eq' | 'NotEq' | 'GreaterThan' | 'LessThan' | 'GreaterThanOrEq' | 'LessThanOrEq' | 'IsNull' | 'IsNotNull';
    };
    updated_at?: {
        $val?: string;
        $op: 'Eq' | 'NotEq' | 'GreaterThan' | 'LessThan' | 'GreaterThanOrEq' | 'LessThanOrEq' | 'IsNull' | 'IsNotNull';
    };
    is_read?: {
        $val?: string | boolean;
        $op: 'Is' | 'IsNot' | 'IsNull' | 'IsNotNull';
    };
};

export type ReadNotificationOrders = {
    id?: 'asc' | 'desc';
    title?: 'asc' | 'desc';
    message?: 'asc' | 'desc';
    link?: 'asc' | 'desc';
    user_id?: 'asc' | 'desc';
    created_at?: 'asc' | 'desc';
    updated_at?: 'asc' | 'desc';
};

export type ReadNotificationQuery = {
    filters?: ReadNotificationFilters;
    relations?: {
        user?: string | boolean | ReadUsersRelations;
    };
    orders?: ReadNotificationOrders;
    pagination?: {
        skip?: string | number;
        take?: string | number;
    };
};

export type ReadNotificationRelations = {
    user?: string | boolean | ReadUsersRelations;
};

export type ReadOneNotificationQuery = {
    relations?: ReadNotificationRelations;
};

export type ReadOneScheduledNotificationQuery = {
    relations?: {
        brand?: string | boolean | ReadBrandsRelations;
    };
};

export type ReadScheduledNotificationFilters = {
    id?: {
        $val?: string | number | Array<string | number>;
        $op: 'Eq' | 'NotEq' | 'GreaterThan' | 'LessThan' | 'GreaterThanOrEq' | 'LessThanOrEq' | 'IsNull' | 'IsNotNull' | 'In' | 'NotIn';
    };
    title?: {
        $val?: string | Array<string>;
        $op: 'Eq' | 'NotEq' | 'Contains' | 'StartsWith' | 'EndsWith' | 'IsNull' | 'IsNotNull' | 'In' | 'NotIn';
    };
    message?: {
        $val?: string | Array<string>;
        $op: 'Eq' | 'NotEq' | 'Contains' | 'StartsWith' | 'EndsWith' | 'IsNull' | 'IsNotNull' | 'In' | 'NotIn';
    };
    link?: {
        $val?: string | Array<string>;
        $op: 'Eq' | 'NotEq' | 'Contains' | 'StartsWith' | 'EndsWith' | 'IsNull' | 'IsNotNull' | 'In' | 'NotIn';
    };
    brand_id?: {
        $val?: string | number | Array<string | number>;
        $op: 'Eq' | 'NotEq' | 'GreaterThan' | 'LessThan' | 'GreaterThanOrEq' | 'LessThanOrEq' | 'IsNull' | 'IsNotNull' | 'In' | 'NotIn';
    };
    type?: {
        $val?: string | Array<string>;
        $op: 'Eq' | 'NotEq' | 'Contains' | 'StartsWith' | 'EndsWith' | 'IsNull' | 'IsNotNull' | 'In' | 'NotIn';
    };
    status?: {
        $val?: string | Array<string>;
        $op: 'Eq' | 'NotEq' | 'Contains' | 'StartsWith' | 'EndsWith' | 'IsNull' | 'IsNotNull' | 'In' | 'NotIn';
    };
    schedule_at?: {
        $val?: string;
        $op: 'Eq' | 'NotEq' | 'GreaterThan' | 'LessThan' | 'GreaterThanOrEq' | 'LessThanOrEq' | 'IsNull' | 'IsNotNull';
    };
    processed_count?: {
        $val?: string | number | Array<string | number>;
        $op: 'Eq' | 'NotEq' | 'GreaterThan' | 'LessThan' | 'GreaterThanOrEq' | 'LessThanOrEq' | 'IsNull' | 'IsNotNull' | 'In' | 'NotIn';
    };
    failed_count?: {
        $val?: string | number | Array<string | number>;
        $op: 'Eq' | 'NotEq' | 'GreaterThan' | 'LessThan' | 'GreaterThanOrEq' | 'LessThanOrEq' | 'IsNull' | 'IsNotNull' | 'In' | 'NotIn';
    };
    processed_at?: {
        $val?: string;
        $op: 'Eq' | 'NotEq' | 'GreaterThan' | 'LessThan' | 'GreaterThanOrEq' | 'LessThanOrEq' | 'IsNull' | 'IsNotNull';
    };
    created_at?: {
        $val?: string;
        $op: 'Eq' | 'NotEq' | 'GreaterThan' | 'LessThan' | 'GreaterThanOrEq' | 'LessThanOrEq' | 'IsNull' | 'IsNotNull';
    };
    updated_at?: {
        $val?: string;
        $op: 'Eq' | 'NotEq' | 'GreaterThan' | 'LessThan' | 'GreaterThanOrEq' | 'LessThanOrEq' | 'IsNull' | 'IsNotNull';
    };
};

export type ReadScheduledNotificationOrders = {
    id?: 'asc' | 'desc';
    title?: 'asc' | 'desc';
    message?: 'asc' | 'desc';
    link?: 'asc' | 'desc';
    brand_id?: 'asc' | 'desc';
    type?: 'asc' | 'desc';
    status?: 'asc' | 'desc';
    schedule_at?: 'asc' | 'desc';
    processed_count?: 'asc' | 'desc';
    failed_count?: 'asc' | 'desc';
    processed_at?: 'asc' | 'desc';
    created_at?: 'asc' | 'desc';
    updated_at?: 'asc' | 'desc';
};

export type ReadScheduledNotificationQuery = {
    filters?: ReadScheduledNotificationFilters;
    relations?: {
        brand?: string | boolean | ReadBrandsRelations;
    };
    orders?: ReadScheduledNotificationOrders;
    pagination?: {
        skip?: string | number;
        take?: string | number;
    };
};

export type ReadScheduledNotificationRelations = {
    brand?: string | boolean | ReadBrandsRelations;
};

export type UpdateNotification = {
    title?: string;
    message?: string;
    link?: string;
    user_id?: number;
    brand_id?: number;
};

export type CreateOnboardingImages = {
    image_id: number;
    display_order?: number;
};

export type ReadOnboardingImagesFilters = {
    id?: {
        $val?: string | number | Array<string | number>;
        $op: 'Eq' | 'NotEq' | 'GreaterThan' | 'LessThan' | 'GreaterThanOrEq' | 'LessThanOrEq' | 'IsNull' | 'IsNotNull' | 'In' | 'NotIn';
    };
    image_id?: {
        $val?: string | number | Array<string | number>;
        $op: 'Eq' | 'NotEq' | 'GreaterThan' | 'LessThan' | 'GreaterThanOrEq' | 'LessThanOrEq' | 'IsNull' | 'IsNotNull' | 'In' | 'NotIn';
    };
    display_order?: {
        $val?: string | number | Array<string | number>;
        $op: 'Eq' | 'NotEq' | 'GreaterThan' | 'LessThan' | 'GreaterThanOrEq' | 'LessThanOrEq' | 'IsNull' | 'IsNotNull' | 'In' | 'NotIn';
    };
    created_at?: {
        $val?: string;
        $op: 'Eq' | 'NotEq' | 'GreaterThan' | 'LessThan' | 'GreaterThanOrEq' | 'LessThanOrEq' | 'IsNull' | 'IsNotNull';
    };
    updated_at?: {
        $val?: string;
        $op: 'Eq' | 'NotEq' | 'GreaterThan' | 'LessThan' | 'GreaterThanOrEq' | 'LessThanOrEq' | 'IsNull' | 'IsNotNull';
    };
};

export type ReadOnboardingImagesOrders = {
    id?: 'asc' | 'desc';
    image_id?: 'asc' | 'desc';
    display_order?: 'asc' | 'desc';
    created_at?: 'asc' | 'desc';
    updated_at?: 'asc' | 'desc';
};

export type ReadOnboardingImagesQuery = {
    filters?: ReadOnboardingImagesFilters;
    relations?: {
        image?: string | boolean | ReadMediaRelations;
    };
    orders?: ReadOnboardingImagesOrders;
    pagination?: {
        skip?: string | number;
        take?: string | number;
    };
};

export type ReadOnboardingImagesRelations = {
    image?: string | boolean | ReadMediaRelations;
};

export type ReadOneOnboardingImagesQuery = {
    relations?: ReadOnboardingImagesRelations;
};

export type ReorderOnboardingImages = {
    images: Array<{
        id: number;
        display_order: number;
    }>;
};

export type UpdateOnboardingImages = {
    image_id?: number;
    display_order?: number;
};

export type CreateTerms = {
    terms: string;
    policy: string;
    terms_id_terms_translations: Array<{
        terms: string;
        policy: string;
        language: 'ar' | 'en';
    }>;
};

export type ReadOneTermsQuery = {
    relations?: {
        terms_id_terms_translations?: boolean;
    };
};

export type ReadTermsFilters = {
    id?: {
        $op: 'Eq' | 'NotEq' | 'GreaterThan' | 'LessThan' | 'GreaterThanOrEq' | 'LessThanOrEq' | 'IsNull' | 'IsNotNull' | 'In' | 'NotIn';
        $val: number;
    };
    version?: {
        $op: 'Eq' | 'NotEq' | 'Contains' | 'StartsWith' | 'EndsWith' | 'IsNull' | 'IsNotNull' | 'In' | 'NotIn';
        $val: string;
    };
    is_active?: {
        $op: 'Is' | 'IsNot' | 'IsNull' | 'IsNotNull';
        $val: boolean;
    };
};

export type ReadTermsOrders = {
    id?: 'asc' | 'desc';
    created_at?: 'asc' | 'desc';
    updated_at?: 'asc' | 'desc';
};

export type ReadTermsQuery = {
    filters?: ReadTermsFilters;
    orders?: ReadTermsOrders;
    relations?: {
        terms_id_terms_translations?: boolean;
    };
};

export type ReadTermsRelations = {
    terms_id_terms_translations?: boolean;
};

export type UpdateTerms = {
    terms?: string;
    policy?: string;
    terms_id_terms_translations?: Array<{
        id?: number | null;
        terms_id?: number | null;
        terms: string;
        policy: string;
        language: 'ar' | 'en';
    }>;
};

export type ReadOneUsersQuery = {
    relations?: {
        profile_image: string | boolean;
    };
};

export type ReadUsersFilters = {
    id?: {
        $val?: string | number | Array<string | number>;
        $op: 'Eq' | 'NotEq' | 'GreaterThan' | 'LessThan' | 'GreaterThanOrEq' | 'LessThanOrEq' | 'IsNull' | 'IsNotNull' | 'In' | 'NotIn';
    } | null;
    password?: {
        $val?: string | Array<string>;
        $op: 'Eq' | 'NotEq' | 'Contains' | 'StartsWith' | 'EndsWith' | 'IsNull' | 'IsNotNull' | 'In' | 'NotIn';
    } | null;
    name?: {
        $val?: string | Array<string>;
        $op: 'Eq' | 'NotEq' | 'Contains' | 'StartsWith' | 'EndsWith' | 'IsNull' | 'IsNotNull' | 'In' | 'NotIn';
    } | null;
    phone_number?: {
        $val?: string | Array<string>;
        $op: 'Eq' | 'NotEq' | 'Contains' | 'StartsWith' | 'EndsWith' | 'IsNull' | 'IsNotNull' | 'In' | 'NotIn';
    } | null;
    phone_number_key?: {
        $val?: string | Array<string>;
        $op: 'Eq' | 'NotEq' | 'Contains' | 'StartsWith' | 'EndsWith' | 'IsNull' | 'IsNotNull' | 'In' | 'NotIn';
    } | null;
    email?: {
        $val?: string | Array<string>;
        $op: 'Eq' | 'NotEq' | 'Contains' | 'StartsWith' | 'EndsWith' | 'IsNull' | 'IsNotNull' | 'In' | 'NotIn';
    } | null;
    verification_code?: {
        $val?: string | Array<string>;
        $op: 'Eq' | 'NotEq' | 'Contains' | 'StartsWith' | 'EndsWith' | 'IsNull' | 'IsNotNull' | 'In' | 'NotIn';
    } | null;
    verification_code_expire_at?: {
        $val?: string;
        $op: 'Eq' | 'NotEq' | 'GreaterThan' | 'LessThan' | 'GreaterThanOrEq' | 'LessThanOrEq' | 'IsNull' | 'IsNotNull';
    } | null;
    account_verified?: {
        $val?: string | boolean;
        $op: 'Is' | 'IsNot' | 'IsNull' | 'IsNotNull';
    } | null;
    verification_reason?: {
        $val?: string | Array<string>;
        $op: 'Eq' | 'NotEq' | 'Contains' | 'StartsWith' | 'EndsWith' | 'IsNull' | 'IsNotNull' | 'In' | 'NotIn';
    } | null;
    apple_token?: {
        $val?: string | Array<string>;
        $op: 'Eq' | 'NotEq' | 'Contains' | 'StartsWith' | 'EndsWith' | 'IsNull' | 'IsNotNull' | 'In' | 'NotIn';
    } | null;
    google_token?: {
        $val?: string | Array<string>;
        $op: 'Eq' | 'NotEq' | 'Contains' | 'StartsWith' | 'EndsWith' | 'IsNull' | 'IsNotNull' | 'In' | 'NotIn';
    } | null;
    facebook_token?: {
        $val?: string | Array<string>;
        $op: 'Eq' | 'NotEq' | 'Contains' | 'StartsWith' | 'EndsWith' | 'IsNull' | 'IsNotNull' | 'In' | 'NotIn';
    } | null;
    access_token?: {
        $val?: string | Array<string>;
        $op: 'Eq' | 'NotEq' | 'Contains' | 'StartsWith' | 'EndsWith' | 'IsNull' | 'IsNotNull' | 'In' | 'NotIn';
    } | null;
    de_square_token?: {
        $val?: string | Array<string>;
        $op: 'Eq' | 'NotEq' | 'Contains' | 'StartsWith' | 'EndsWith' | 'IsNull' | 'IsNotNull' | 'In' | 'NotIn';
    } | null;
    de_square_token_expire_at?: {
        $val?: string;
        $op: 'Eq' | 'NotEq' | 'GreaterThan' | 'LessThan' | 'GreaterThanOrEq' | 'LessThanOrEq' | 'IsNull' | 'IsNotNull';
    } | null;
    role?: {
        $val?: string | Array<string>;
        $op: 'Eq' | 'NotEq' | 'Contains' | 'StartsWith' | 'EndsWith' | 'IsNull' | 'IsNotNull' | 'In' | 'NotIn';
    } | null;
    rank?: {
        $val?: string | number | Array<string | number>;
        $op: 'Eq' | 'NotEq' | 'GreaterThan' | 'LessThan' | 'GreaterThanOrEq' | 'LessThanOrEq' | 'IsNull' | 'IsNotNull' | 'In' | 'NotIn';
    } | null;
    birthdate?: {
        $val?: string;
        $op: 'Eq' | 'NotEq' | 'GreaterThan' | 'LessThan' | 'GreaterThanOrEq' | 'LessThanOrEq' | 'IsNull' | 'IsNotNull';
    } | null;
    is_logged_in?: {
        $val?: string | boolean;
        $op: 'Is' | 'IsNot' | 'IsNull' | 'IsNotNull';
    } | null;
    created_at?: {
        $val?: string;
        $op: 'Eq' | 'NotEq' | 'GreaterThan' | 'LessThan' | 'GreaterThanOrEq' | 'LessThanOrEq' | 'IsNull' | 'IsNotNull';
    } | null;
    updated_at?: {
        $val?: string;
        $op: 'Eq' | 'NotEq' | 'GreaterThan' | 'LessThan' | 'GreaterThanOrEq' | 'LessThanOrEq' | 'IsNull' | 'IsNotNull';
    } | null;
};

export type ReadUsersOrders = {
    id?: 'asc' | 'desc';
    password?: 'asc' | 'desc';
    name?: 'asc' | 'desc';
    phone_number?: 'asc' | 'desc';
    phone_number_key?: 'asc' | 'desc';
    email?: 'asc' | 'desc';
    verification_code?: 'asc' | 'desc';
    verification_code_expire_at?: 'asc' | 'desc';
    account_verified?: 'asc' | 'desc';
    verification_reason?: 'asc' | 'desc';
    apple_token?: 'asc' | 'desc';
    google_token?: 'asc' | 'desc';
    facebook_token?: 'asc' | 'desc';
    access_token?: 'asc' | 'desc';
    de_square_token?: 'asc' | 'desc';
    de_square_token_expire_at?: 'asc' | 'desc';
    role?: 'asc' | 'desc';
    birthdate?: 'asc' | 'desc';
    created_at?: 'asc' | 'desc';
    updated_at?: 'asc' | 'desc';
};

export type ReadUsersQuery = {
    filters?: ReadUsersFilters;
    relations?: {
        profile_image: string | boolean;
    };
    orders?: ReadUsersOrders;
    pagination?: {
        skip?: string | number;
        take?: string | number;
    };
};

export type ReadUsersRelations = {
    profile_image: string | boolean;
};

export type UpdateProfile = {
    profile_image?: number;
    name?: string;
    password?: string;
    fcm_token?: string;
    rank?: 1 | 2 | 3;
    birthdate?: string;
};

export type UpdateUiConfig = {
    [key: string]: boolean | string | Array<string>;
};

export type ValidateParamId = {
    id: string | number;
};

export type AppControllerEntryData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type AppControllerEntryResponses = {
    200: string;
};

export type AppControllerEntryResponse = AppControllerEntryResponses[keyof AppControllerEntryResponses];

export type ContactUsControllerReadData = {
    body?: never;
    path?: never;
    query: {
        /**
         * The query to be used to read all ContactUs.
         */
        query: ReadContactUsQuery;
    };
    url: '/contact-us';
};

export type ContactUsControllerReadResponses = {
    /**
     * The ContactUs have been successfully read.
     */
    200: {
        data?: Array<ContactUsEntity>;
        meta?: {
            total?: number;
            skip?: number;
            take?: number;
        };
    };
};

export type ContactUsControllerReadResponse = ContactUsControllerReadResponses[keyof ContactUsControllerReadResponses];

export type ContactUsControllerCreateData = {
    /**
     * The ContactUs to be created.
     */
    body: CreateContactUs;
    path?: never;
    query?: never;
    url: '/contact-us';
};

export type ContactUsControllerCreateResponses = {
    /**
     * The ContactUs has been successfully created.
     */
    201: {
        data?: ContactUsEntity;
    };
};

export type ContactUsControllerCreateResponse = ContactUsControllerCreateResponses[keyof ContactUsControllerCreateResponses];

export type ContactUsControllerUpdateData = {
    /**
     * The ContactUs to be updated.
     */
    body: UpdateContactUs;
    path: {
        id: string;
    };
    query?: never;
    url: '/contact-us/{id}';
};

export type ContactUsControllerUpdateResponses = {
    /**
     * The ContactUs has been successfully updated.
     */
    200: {
        data?: ContactUsEntity;
    };
};

export type ContactUsControllerUpdateResponse = ContactUsControllerUpdateResponses[keyof ContactUsControllerUpdateResponses];

export type AuthControllerVerifyOtpData = {
    /**
     * The OTP verification data.
     */
    body: unknown;
    path?: never;
    query?: never;
    url: '/auth/verify-otp';
};

export type AuthControllerVerifyOtpResponses = {
    /**
     * The OTP has been successfully verified.
     */
    200: unknown;
};

export type AuthControllerResendOtpData = {
    /**
     * The OTP resend request data.
     */
    body: unknown;
    path?: never;
    query?: never;
    url: '/auth/resend-otp';
};

export type AuthControllerResendOtpResponses = {
    /**
     * The OTP has been successfully resent.
     */
    200: unknown;
};

export type AuthControllerSigninData = {
    /**
     * The signin credentials.
     */
    body: unknown;
    path?: never;
    query?: never;
    url: '/auth/signin';
};

export type AuthControllerSigninResponses = {
    /**
     * The signin has been successfully completed.
     */
    200: unknown;
};

export type AuthControllerForgetPasswordData = {
    /**
     * The forget password request data.
     */
    body: unknown;
    path?: never;
    query?: never;
    url: '/auth/forget-password';
};

export type AuthControllerForgetPasswordResponses = {
    /**
     * The forget password request has been successfully processed.
     */
    200: unknown;
};

export type AuthControllerCompleteForgetPasswordData = {
    /**
     * The complete forget password data.
     */
    body: unknown;
    path?: never;
    query?: never;
    url: '/auth/complete-forget-password';
};

export type AuthControllerCompleteForgetPasswordResponses = {
    /**
     * The forget password has been successfully completed.
     */
    200: unknown;
};

export type AuthControllerSignupData = {
    /**
     * The user registration data.
     */
    body: unknown;
    path?: never;
    query?: never;
    url: '/auth/signup';
};

export type AuthControllerSignupResponses = {
    /**
     * The signup has been successfully completed.
     */
    200: unknown;
};

export type AuthControllerSignoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/signout';
};

export type AuthControllerSignoutResponses = {
    /**
     * The user has been successfully signed out.
     */
    200: unknown;
};

export type AuthControllerGetSessionDataData = {
    body?: never;
    path: {
        /**
         * The session ID to retrieve data for.
         */
        session_id: string;
    };
    query?: never;
    url: '/auth/get-session-data/{session_id}';
};

export type AuthControllerGetSessionDataResponses = {
    /**
     * The session data has been successfully retrieved.
     */
    200: unknown;
};

export type AuthControllerCompletePhoneNumberData = {
    /**
     * The phone number completion data. Name is optional and will be updated if provided.
     */
    body: unknown;
    path?: never;
    query?: never;
    url: '/auth/complete-phone-number';
};

export type AuthControllerCompletePhoneNumberResponses = {
    /**
     * The phone number has been successfully completed.
     */
    200: unknown;
};

export type AuthControllerAskUpdatePhoneNumberData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/ask-update-phone-number';
};

export type AuthControllerAskUpdatePhoneNumberResponses = {
    200: unknown;
};

export type AuthControllerAskUpdateEmailData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/ask-update-email';
};

export type AuthControllerAskUpdateEmailResponses = {
    200: unknown;
};

export type AuthControllerUpdatePhoneNumberData = {
    /**
     * The phone number completion data.
     */
    body: unknown;
    path?: never;
    query?: never;
    url: '/auth/update-phone-number';
};

export type AuthControllerUpdatePhoneNumberResponses = {
    200: unknown;
};

export type AuthControllerUpdateEmailData = {
    /**
     * The phone number completion data.
     */
    body: unknown;
    path?: never;
    query?: never;
    url: '/auth/update-email';
};

export type AuthControllerUpdateEmailResponses = {
    200: unknown;
};

export type AuthControllerRefreshTokenData = {
    /**
     * The refresh token data.
     */
    body: RefreshToken;
    path?: never;
    query?: never;
    url: '/auth/refresh-token';
};

export type AuthControllerRefreshTokenResponses = {
    /**
     * Token refreshed successfully.
     */
    200: RefreshTokenResponse;
};

export type AuthControllerRefreshTokenResponse = AuthControllerRefreshTokenResponses[keyof AuthControllerRefreshTokenResponses];

export type UsersControllerReadData = {
    body?: never;
    path?: never;
    query: {
        /**
         * The query to be used to read all Users.
         */
        query: ReadUsersQuery;
    };
    url: '/users';
};

export type UsersControllerReadResponses = {
    /**
     * The Users has been successfully read.
     */
    200: {
        data?: Array<UsersEntity>;
        meta?: {
            total?: number;
            skip?: number;
            take?: number;
        };
    };
};

export type UsersControllerReadResponse = UsersControllerReadResponses[keyof UsersControllerReadResponses];

export type UsersControllerDeleteData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/users/{id}';
};

export type UsersControllerDeleteResponses = {
    /**
     * The Users has been successfully soft deleted.
     */
    200: boolean;
};

export type UsersControllerDeleteResponse = UsersControllerDeleteResponses[keyof UsersControllerDeleteResponses];

export type UsersControllerReadOneData = {
    body?: never;
    path: {
        id: string;
    };
    query: {
        /**
         * The query to be used to read one Users.
         */
        query: ReadOneUsersQuery;
    };
    url: '/users/{id}';
};

export type UsersControllerReadOneResponses = {
    /**
     * The Users has been successfully read.
     */
    200: {
        data?: UsersEntity;
    };
};

export type UsersControllerReadOneResponse = UsersControllerReadOneResponses[keyof UsersControllerReadOneResponses];

export type UsersControllerDeleteProfileData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/profile';
};

export type UsersControllerDeleteProfileResponses = {
    200: unknown;
};

export type UsersControllerGetProfileData = {
    body?: never;
    path?: never;
    query: {
        /**
         * The query to be used to read one Users.
         */
        query: ReadOneUsersQuery;
    };
    url: '/users/profile';
};

export type UsersControllerGetProfileResponses = {
    /**
     * The Users has been successfully read.
     */
    200: {
        data?: UsersEntity;
    };
};

export type UsersControllerGetProfileResponse = UsersControllerGetProfileResponses[keyof UsersControllerGetProfileResponses];

export type UsersControllerUpdateProfileData = {
    body?: never;
    path?: never;
    query: {
        /**
         * The query to be used to update one Users.
         */
        query: unknown;
    };
    url: '/users/profile';
};

export type UsersControllerUpdateProfileResponses = {
    /**
     * The Users has been successfully updated.
     */
    200: {
        data?: UsersEntity;
    };
};

export type UsersControllerUpdateProfileResponse = UsersControllerUpdateProfileResponses[keyof UsersControllerUpdateProfileResponses];

export type UsersControllerGetUiConfigData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/profile/ui-config';
};

export type UsersControllerGetUiConfigResponses = {
    /**
     * The UI configurations have been successfully retrieved.
     */
    200: unknown;
};

export type UsersControllerUpdateUiConfigData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/profile/ui-config';
};

export type UsersControllerUpdateUiConfigResponses = {
    /**
     * The UI configurations have been successfully updated.
     */
    200: unknown;
};

export type MediaControllerUploadFileData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/media/upload';
};

export type MediaControllerUploadFileResponses = {
    /**
     * File uploaded successfully
     */
    201: MediaEntity;
};

export type MediaControllerUploadFileResponse = MediaControllerUploadFileResponses[keyof MediaControllerUploadFileResponses];

export type MediaControllerUpdateFileData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/media/upload/{id}';
};

export type MediaControllerUpdateFileResponses = {
    /**
     * File updated successfully
     */
    200: MediaEntity;
};

export type MediaControllerUpdateFileResponse = MediaControllerUpdateFileResponses[keyof MediaControllerUpdateFileResponses];

export type MediaControllerReadOneData = {
    body?: never;
    path: {
        id: string;
    };
    query: {
        /**
         * The query to be used to read one Media.
         */
        query: ReadOneMediaQuery;
    };
    url: '/media/{id}';
};

export type MediaControllerReadOneResponses = {
    /**
     * The Media has been successfully read.
     */
    200: {
        data?: MediaEntity;
    };
};

export type MediaControllerReadOneResponse = MediaControllerReadOneResponses[keyof MediaControllerReadOneResponses];

export type MediaControllerStreamMediaData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/media/{id}/stream';
};

export type MediaControllerStreamMediaErrors = {
    /**
     * Media file not found.
     */
    404: unknown;
};

export type MediaControllerStreamMediaResponses = {
    /**
     * The Media file is being streamed.
     */
    200: unknown;
    /**
     * Partial content is being streamed (for range requests).
     */
    206: unknown;
};

export type TermsControllerReadData = {
    body?: never;
    path?: never;
    query: {
        /**
         * The query to be used to read all Terms.
         */
        query: ReadTermsQuery;
    };
    url: '/terms';
};

export type TermsControllerReadResponses = {
    /**
     * The Terms has been successfully read.
     */
    200: {
        data?: Array<TermsEntity>;
        meta?: {
            total?: number;
            skip?: number;
            take?: number;
        };
    };
};

export type TermsControllerReadResponse = TermsControllerReadResponses[keyof TermsControllerReadResponses];

export type TermsControllerCreateData = {
    /**
     * The Terms to be created.
     */
    body: CreateTerms;
    path?: never;
    query?: never;
    url: '/terms';
};

export type TermsControllerCreateResponses = {
    /**
     * The Terms has been successfully created.
     */
    201: {
        data?: TermsEntity;
    };
};

export type TermsControllerCreateResponse = TermsControllerCreateResponses[keyof TermsControllerCreateResponses];

export type TermsControllerReadOneData = {
    body?: never;
    path: {
        id: string;
    };
    query: {
        /**
         * The query to be used to read one Terms.
         */
        query: ReadOneTermsQuery;
    };
    url: '/terms/{id}';
};

export type TermsControllerReadOneResponses = {
    /**
     * The Terms has been successfully read.
     */
    200: {
        data?: TermsEntity;
    };
};

export type TermsControllerReadOneResponse = TermsControllerReadOneResponses[keyof TermsControllerReadOneResponses];

export type TermsControllerUpdateData = {
    /**
     * The Terms to be updated.
     */
    body: UpdateTerms;
    path: {
        id: string;
    };
    query?: never;
    url: '/terms/{id}';
};

export type TermsControllerUpdateResponses = {
    /**
     * The Terms has been successfully updated.
     */
    200: {
        data?: TermsEntity;
    };
};

export type TermsControllerUpdateResponse = TermsControllerUpdateResponses[keyof TermsControllerUpdateResponses];

export type TermsControllerReadActiveData = {
    body?: never;
    path?: never;
    query: {
        /**
         * The query to be used to read active Terms.
         */
        query: ReadOneTermsQuery;
    };
    url: '/terms/active';
};

export type TermsControllerReadActiveResponses = {
    /**
     * The active Terms has been successfully read.
     */
    200: {
        data?: TermsEntity;
    };
};

export type TermsControllerReadActiveResponse = TermsControllerReadActiveResponses[keyof TermsControllerReadActiveResponses];

export type BrandsControllerReadData = {
    body?: never;
    path?: never;
    query: {
        /**
         * The query to be used to read all Brands.
         */
        query: ReadBrandsQuery;
    };
    url: '/brands';
};

export type BrandsControllerReadResponses = {
    /**
     * The Brands has been successfully read.
     */
    200: {
        data?: Array<BrandsEntity>;
        meta?: {
            total?: number;
            skip?: number;
            take?: number;
        };
    };
};

export type BrandsControllerReadResponse = BrandsControllerReadResponses[keyof BrandsControllerReadResponses];

export type BrandsControllerCreateData = {
    /**
     * The Brand to be created.
     */
    body: CreateBrands;
    path?: never;
    query?: never;
    url: '/brands';
};

export type BrandsControllerCreateResponses = {
    /**
     * The Brand has been successfully created.
     */
    201: {
        data?: BrandsEntity;
    };
};

export type BrandsControllerCreateResponse = BrandsControllerCreateResponses[keyof BrandsControllerCreateResponses];

export type BrandsControllerReadOneData = {
    body?: never;
    path: {
        id: string;
    };
    query: {
        /**
         * The query to be used to read one Brand.
         */
        query: ReadOneBrandsQuery;
    };
    url: '/brands/{id}';
};

export type BrandsControllerReadOneResponses = {
    /**
     * The Brand has been successfully read.
     */
    200: {
        data?: BrandsEntity;
    };
};

export type BrandsControllerReadOneResponse = BrandsControllerReadOneResponses[keyof BrandsControllerReadOneResponses];

export type BrandsControllerUpdateData = {
    /**
     * The Brand to be updated.
     */
    body: UpdateBrands;
    path: {
        id: string;
    };
    query?: never;
    url: '/brands/{id}';
};

export type BrandsControllerUpdateResponses = {
    /**
     * The Brand has been successfully updated.
     */
    200: {
        data?: BrandsEntity;
    };
};

export type BrandsControllerUpdateResponse = BrandsControllerUpdateResponses[keyof BrandsControllerUpdateResponses];

export type BrandsControllerSoftDeleteData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/brands/{id}/soft';
};

export type BrandsControllerSoftDeleteResponses = {
    /**
     * The Brand has been successfully soft deleted.
     */
    200: boolean;
};

export type BrandsControllerSoftDeleteResponse = BrandsControllerSoftDeleteResponses[keyof BrandsControllerSoftDeleteResponses];

export type BrandsControllerReorderData = {
    /**
     * Reorder brands by providing an array of brand IDs with their new display order.
     */
    body: ReorderBrands;
    path?: never;
    query?: never;
    url: '/brands/reorder';
};

export type BrandsControllerReorderResponses = {
    /**
     * The Brands have been successfully reordered.
     */
    200: unknown;
};

export type BannersControllerReadData = {
    body?: never;
    path?: never;
    query: {
        /**
         * The query to be used to read all Banners.
         */
        query: ReadBannersQuery;
    };
    url: '/banners';
};

export type BannersControllerReadResponses = {
    /**
     * The Banners have been successfully read.
     */
    200: {
        data?: Array<BannersEntity>;
        meta?: {
            total?: number;
            skip?: number;
            take?: number;
        };
    };
};

export type BannersControllerReadResponse = BannersControllerReadResponses[keyof BannersControllerReadResponses];

export type BannersControllerCreateData = {
    /**
     * The Banner to be created.
     */
    body: CreateBanners;
    path?: never;
    query?: never;
    url: '/banners';
};

export type BannersControllerCreateResponses = {
    /**
     * The Banner has been successfully created.
     */
    201: {
        data?: BannersEntity;
    };
};

export type BannersControllerCreateResponse = BannersControllerCreateResponses[keyof BannersControllerCreateResponses];

export type BannersControllerUpdateData = {
    /**
     * The Banner to be updated.
     */
    body: UpdateBanners;
    path: {
        id: string;
    };
    query?: never;
    url: '/banners/{id}';
};

export type BannersControllerUpdateResponses = {
    /**
     * The Banner has been successfully updated.
     */
    200: {
        data?: BannersEntity;
    };
};

export type BannersControllerUpdateResponse = BannersControllerUpdateResponses[keyof BannersControllerUpdateResponses];

export type BannersControllerSoftDeleteData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/banners/{id}/soft';
};

export type BannersControllerSoftDeleteResponses = {
    /**
     * The Banner has been successfully soft deleted.
     */
    200: boolean;
};

export type BannersControllerSoftDeleteResponse = BannersControllerSoftDeleteResponses[keyof BannersControllerSoftDeleteResponses];

export type NotificationControllerCreateBarqData = {
    /**
     * The Barq Notification to be created.
     */
    body: CreateBarqNotification;
    path?: never;
    query?: never;
    url: '/notifications/stars';
};

export type NotificationControllerCreateBarqResponses = {
    /**
     * The Barq Notification has been successfully created.
     */
    201: {
        data?: NotificationsEntity;
    };
};

export type NotificationControllerCreateBarqResponse = NotificationControllerCreateBarqResponses[keyof NotificationControllerCreateBarqResponses];

export type NotificationControllerReadData = {
    body?: never;
    path?: never;
    query: {
        /**
         * The query to be used to read all Notifications.
         */
        query: ReadNotificationQuery;
    };
    url: '/notifications';
};

export type NotificationControllerReadResponses = {
    /**
     * The Notifications has been successfully read.
     */
    200: {
        data?: Array<NotificationsEntity>;
        meta?: {
            total?: number;
            skip?: number;
            take?: number;
        };
    };
};

export type NotificationControllerReadResponse = NotificationControllerReadResponses[keyof NotificationControllerReadResponses];

export type NotificationControllerCreateData = {
    /**
     * The Notification to be created. You can send to specific users (users array), users with specific ranks (ranks array), or both (intersection - selected users who have the specified ranks). Ranks: 1=Silver, 2=Gold, 3=Platinum.
     */
    body: CreateNotification;
    path?: never;
    query?: never;
    url: '/notifications';
};

export type NotificationControllerCreateResponses = {
    /**
     * The Notification has been successfully created.
     */
    201: {
        data?: NotificationsEntity;
    };
};

export type NotificationControllerCreateResponse = NotificationControllerCreateResponses[keyof NotificationControllerCreateResponses];

export type NotificationControllerReadOneData = {
    body?: never;
    path: {
        id: string;
    };
    query: {
        /**
         * The query to be used to read one Notification.
         */
        query: ReadOneNotificationQuery;
    };
    url: '/notifications/{id}';
};

export type NotificationControllerReadOneResponses = {
    /**
     * The Notification has been successfully read.
     */
    200: {
        data?: NotificationsEntity;
    };
};

export type NotificationControllerReadOneResponse = NotificationControllerReadOneResponses[keyof NotificationControllerReadOneResponses];

export type NotificationControllerSoftDeleteData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/notifications/{id}/soft';
};

export type NotificationControllerSoftDeleteResponses = {
    /**
     * The Notification has been successfully soft deleted.
     */
    200: boolean;
};

export type NotificationControllerSoftDeleteResponse = NotificationControllerSoftDeleteResponses[keyof NotificationControllerSoftDeleteResponses];

export type NotificationControllerGetMyNotificationsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/notifications/my';
};

export type NotificationControllerGetMyNotificationsResponses = {
    /**
     * The Notifications has been successfully read.
     */
    200: {
        data?: Array<NotificationsEntity>;
        meta?: {
            total?: number;
            skip?: number;
            take?: number;
        };
    };
};

export type NotificationControllerGetMyNotificationsResponse = NotificationControllerGetMyNotificationsResponses[keyof NotificationControllerGetMyNotificationsResponses];

export type NotificationControllerBroadcastData = {
    /**
     * The Notification to be broadcasted to all users. If ranks is provided, notification will be sent only to users with those ranks (1=Silver, 2=Gold, 3=Platinum). If ranks is not provided, notification will be sent to all users.
     */
    body: {
        title: string;
        message: string;
        link?: string;
        /**
         * Optional array of rank filters (1=Silver, 2=Gold, 3=Platinum). If provided, notification will be sent only to users with these ranks.
         */
        ranks?: Array<1 | 2 | 3>;
    };
    path?: never;
    query?: never;
    url: '/notifications/broadcast';
};

export type NotificationControllerBroadcastResponses = {
    /**
     * The Notification has been successfully broadcasted.
     */
    201: {
        data?: Array<NotificationsEntity>;
        count?: number;
    };
};

export type NotificationControllerBroadcastResponse = NotificationControllerBroadcastResponses[keyof NotificationControllerBroadcastResponses];

export type NotificationControllerMarkAllAsReadData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/notifications/read-all';
};

export type NotificationControllerMarkAllAsReadResponses = {
    /**
     * All notifications have been successfully marked as read.
     */
    200: {
        affected?: number;
    };
};

export type NotificationControllerMarkAllAsReadResponse = NotificationControllerMarkAllAsReadResponses[keyof NotificationControllerMarkAllAsReadResponses];

export type NotificationControllerUpdateData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/notifications/{id}/read';
};

export type NotificationControllerUpdateResponses = {
    /**
     * The Notification has been successfully read.
     */
    200: boolean;
};

export type NotificationControllerUpdateResponse = NotificationControllerUpdateResponses[keyof NotificationControllerUpdateResponses];

export type ScheduledNotificationControllerReadData = {
    body?: never;
    path?: never;
    query: {
        /**
         * The query to be used to read all Scheduled Notifications.
         */
        query: ReadScheduledNotificationQuery;
    };
    url: '/scheduled-notifications';
};

export type ScheduledNotificationControllerReadResponses = {
    /**
     * The Scheduled Notifications have been successfully read.
     */
    200: {
        data?: Array<ScheduledNotificationsEntity>;
        meta?: {
            total?: number;
            skip?: number;
            take?: number;
        };
    };
};

export type ScheduledNotificationControllerReadResponse = ScheduledNotificationControllerReadResponses[keyof ScheduledNotificationControllerReadResponses];

export type ScheduledNotificationControllerReadOneData = {
    body?: never;
    path: {
        id: string;
    };
    query: {
        /**
         * The query to be used to read one Scheduled Notification.
         */
        query: ReadOneScheduledNotificationQuery;
    };
    url: '/scheduled-notifications/{id}';
};

export type ScheduledNotificationControllerReadOneResponses = {
    /**
     * The Scheduled Notification has been successfully read.
     */
    200: {
        data?: ScheduledNotificationsEntity;
    };
};

export type ScheduledNotificationControllerReadOneResponse = ScheduledNotificationControllerReadOneResponses[keyof ScheduledNotificationControllerReadOneResponses];

export type OnboardingImagesControllerReadData = {
    body?: never;
    path?: never;
    query: {
        /**
         * The query to be used to read all Onboarding Images.
         */
        query: ReadOnboardingImagesQuery;
    };
    url: '/onboarding-images';
};

export type OnboardingImagesControllerReadResponses = {
    /**
     * The Onboarding Images have been successfully read.
     */
    200: {
        data?: Array<OnboardingImagesEntity>;
        meta?: {
            total?: number;
            skip?: number;
            take?: number;
        };
    };
};

export type OnboardingImagesControllerReadResponse = OnboardingImagesControllerReadResponses[keyof OnboardingImagesControllerReadResponses];

export type OnboardingImagesControllerCreateData = {
    /**
     * Upload onboarding image with optional display order
     */
    body: {
        file?: Blob | File;
        /**
         * Optional display order (defaults to highest + 1)
         */
        display_order?: number;
    };
    path?: never;
    query?: never;
    url: '/onboarding-images';
};

export type OnboardingImagesControllerCreateResponses = {
    /**
     * The Onboarding Image has been successfully created.
     */
    201: {
        data?: OnboardingImagesEntity;
    };
};

export type OnboardingImagesControllerCreateResponse = OnboardingImagesControllerCreateResponses[keyof OnboardingImagesControllerCreateResponses];

export type OnboardingImagesControllerReadOneData = {
    body?: never;
    path: {
        id: string;
    };
    query: {
        /**
         * The query to be used to read one Onboarding Image.
         */
        query: ReadOneOnboardingImagesQuery;
    };
    url: '/onboarding-images/{id}';
};

export type OnboardingImagesControllerReadOneResponses = {
    /**
     * The Onboarding Image has been successfully read.
     */
    200: {
        data?: OnboardingImagesEntity;
    };
};

export type OnboardingImagesControllerReadOneResponse = OnboardingImagesControllerReadOneResponses[keyof OnboardingImagesControllerReadOneResponses];

export type OnboardingImagesControllerUpdateData = {
    /**
     * The Onboarding Image to be updated.
     */
    body: UpdateOnboardingImages;
    path: {
        id: string;
    };
    query?: never;
    url: '/onboarding-images/{id}';
};

export type OnboardingImagesControllerUpdateResponses = {
    /**
     * The Onboarding Image has been successfully updated.
     */
    200: {
        data?: OnboardingImagesEntity;
    };
};

export type OnboardingImagesControllerUpdateResponse = OnboardingImagesControllerUpdateResponses[keyof OnboardingImagesControllerUpdateResponses];

export type OnboardingImagesControllerReorderData = {
    /**
     * Reorder onboarding images
     */
    body: ReorderOnboardingImages;
    path?: never;
    query?: never;
    url: '/onboarding-images/reorder';
};

export type OnboardingImagesControllerReorderResponses = {
    /**
     * Onboarding images have been successfully reordered.
     */
    200: unknown;
    201: unknown;
};

export type OnboardingImagesControllerSoftDeleteData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/onboarding-images/{id}/soft';
};

export type OnboardingImagesControllerSoftDeleteResponses = {
    /**
     * The Onboarding Image has been successfully soft deleted.
     */
    200: boolean;
};

export type OnboardingImagesControllerSoftDeleteResponse = OnboardingImagesControllerSoftDeleteResponses[keyof OnboardingImagesControllerSoftDeleteResponses];
